name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Log in to dockerhub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build -t mikemoh/nodejs-docker:1.0 .
      - name: Push image to dockerhub
        run: docker push mikemoh/nodejs-docker:1.0

  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Log in to aws
  #       run: dsfs
  #     - name: Pull docker img from dockerhub
  #       run: docker pull mikemoh/nodejs-docker:1.0
  #     - name: Run img in a container
  #       run: docker run mikemoh/nodejs-docker:1.0
  # login to deployment server
# pull docker image from docker hub
# run docker container
